CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists requests (
	id bigint generated by default as identity primary key,
	description varchar,
	requestor_id bigint references users(id) on delete cascade,
	create_date timestamp without time zone default current_timestamp
);

create table if not exists items (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	description varchar,
	is_available boolean,
	owner_id bigint references users (id) on delete cascade,
	request_id bigint references requests(id) on delete cascade
);


create table if not exists bookings (
    id bigint generated by default as identity primary key,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    item_id bigint references items(id) on delete cascade,
    booker_id bigint references users(id) on delete cascade,
    status varchar not null default 'WAITING',
    constraint chk_date check (start_date < end_date)
);

create index if not exists idx_bookings_status on bookings(status);
create index if not exists idx_bookings_start_date on bookings(start_date);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    text text,
    item_id bigint not null references items (id) on delete cascade,
    author_id bigint not null references users(id) on delete cascade,
    created timestamp without time zone not null default current_timestamp
);